<?php

use Illuminate\Support\Str;

return [
    'default' => env('DB_CONNECTION', 'sqlite'),

    'connections' => [
        'jv.de' => [
            'driver' => 'mysql',
            'host' => 'w01da3ea.kasserver.com',
            'port' => '3306',
            'database' => 'd03bcfa4',
            'username' => 'd03bcfa4',
            'password' => 'kk8KBy!!5h0TSLHCa!q',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'main' => [
            'driver' => 'mysql',
            'host' => 'w01e8910.kasserver.com',
            'port' => '3306',
            'database' => 'd04316fe',
            'username' => 'd04316fe',
            'password' => '7KpYL3ZRtb8ryCLuCAUc',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'jv.co.uk' => [
            'driver' => 'mysql',
            'host' => 'w01da3ea.kasserver.com',
            'port' => '3306',
            'database' => 'd03bd42e',
            'username' => 'd03bd42e',
            'password' => 'btLwgjrl0cAgvGGzcv6S',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'jv.ch' => [
            'driver' => 'mysql',
            'host' => 'w01da3ea.kasserver.com',
            'port' => '3306',
            'database' => 'd03bd411',
            'username' => 'd03bd411',
            'password' => '6MIRNTHYXKoPZUWaCzZ2',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'jv.at' => [
            'driver' => 'mysql',
            'host' => 'w01da3ea.kasserver.com',
            'port' => '3306',
            'database' => 'd03bd429',
            'username' => 'd03bd429',
            'password' => 'UiM3rZtVV8wS5PXev5ws',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'b2b.de' => [
            'driver' => 'mysql',
            'host' => 'w01e8910.kasserver.com',
            'port' => '3306',
            'database' => 'd0411446',
            'username' => 'd0411446',
            'password' => 'aegAsmV2HbhaeJ8bER2N',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.be' => [
            'driver' => 'mysql',
            'host' => 'w01e8910.kasserver.com',
            'port' => '3306',
            'database' => 'd04164d1',
            'username' => 'd04164d1',
            'password' => 'Y3brYo6iPvdK6Xd3yJK9',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.de' => [
            'driver' => 'mysql',
            'host' => 'w01e8910.kasserver.com',
            'port' => '3306',
            'database' => 'd03ec5f6',
            'username' => 'd03ec5f6',
            'password' => 'Lu8TaeQz5KTtoo3SBtq7',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.lu' => [
            'driver' => 'mysql',
            'host' => 'w01e8910.kasserver.com',
            'port' => '3306',
            'database' => 'd041f55f',
            'username' => 'd041f55f',
            'password' => 'muuHSx9M4g3x3QxwUDbQ',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.hu' => [
            'driver' => 'mysql',
            'host' => 'w0200990.kasserver.com',
            'port' => '3306',
            'database' => 'd04322df',
            'username' => 'd04322df',
            'password' => 'oLEUzTEkePkfwtWHLGo7',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'dep.ch' => [
            'driver' => 'mysql',
            'host' => 'w0200990.kasserver.com',
            'port' => '3306',
            'database' => 'd0438014',
            'username' => 'd0438014',
            'password' => 'WGMJAxMpD9uAgbAREN48',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.ie' => [
            'driver' => 'mysql',
            'host' => 'w0200990.kasserver.com',
            'port' => '3306',
            'database' => 'd04322e2',
            'username' => 'd04322e2',
            'password' => 'MXtURypVZ5s8YpScPiHx',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.gr' => [
            'driver' => 'mysql',
            'host' => 'w0200990.kasserver.com',
            'port' => '3306',
            'database' => 'd04322e3',
            'username' => 'd04322e3',
            'password' => 'opDZsc5ZAkzNrsCTMBxG',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.ro' => [
            'driver' => 'mysql',
            'host' => 'w0200990.kasserver.com',
            'port' => '3306',
            'database' => 'd04322e4',
            'username' => 'd04322e4',
            'password' => 'Jr5NgL6nCjLsK97ye7Qa',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.fi' => [
            'driver' => 'mysql',
            'host' => 'w01fe1af.kasserver.com',
            'port' => '3306',
            'database' => 'd042add2',
            'username' => 'd042add2',
            'password' => 'zjnCo5J2VV7BVZX884tJ',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.pt' => [
            'driver' => 'mysql',
            'host' => 'w01fe1af.kasserver.com',
            'port' => '3306',
            'database' => 'd042add5',
            'username' => 'd042add5',
            'password' => 'cWCsEfA3352zhxHmbj8R',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.se' => [
            'driver' => 'mysql',
            'host' => 'w01fe1af.kasserver.com',
            'port' => '3306',
            'database' => 'd042c00a',
            'username' => 'd042c00a',
            'password' => 'KAC7SCiMrR6dDn9bWXbx',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.sk' => [
            'driver' => 'mysql',
            'host' => 'w01fe1af.kasserver.com',
            'port' => '3306',
            'database' => 'd042ade0',
            'username' => 'd042ade0',
            'password' => 'NRtDGfjsxJS4BxsJcfAM',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.si' => [
            'driver' => 'mysql',
            'host' => 'w01fe1af.kasserver.com',
            'port' => '3306',
            'database' => 'd042b692',
            'username' => 'd042b692',
            'password' => 'RfA8kzCV3fThdzKm5rjN',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.dk' => [
            'driver' => 'mysql',
            'host' => 'w01fe1af.kasserver.com',
            'port' => '3306',
            'database' => 'd042c867',
            'username' => 'd042c867',
            'password' => 'zX6CyxDf6HgCpQhDoh2S',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'turkey' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd041c861',
            'username' => 'd041c861',
            'password' => 'kPQG3L7GSb9boGQtGYjr',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.co.uk' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd0402e9f',
            'username' => 'd0402e9f',
            'password' => '5PLcgFos2Xny8AdR3Va9',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.pl' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd0402b9e',
            'username' => 'd0402b9e',
            'password' => 'ikdKnQgiXdsGQvJbsz4G',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.fr' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd0408508',
            'username' => 'd0408508',
            'password' => '6MGTk4E2AcqqQp54GaGi',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.at' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd040290a',
            'username' => 'd040290a',
            'password' => 'wRf3KEUB6kGFmeUEk9jt',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.ch' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd04017e9',
            'username' => 'd04017e9',
            'password' => '754BaVkq5cHdhxMML2AJ',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.cz' => [
            'driver' => 'mysql',
            'host' => 'w01ef467.kasserver.com',
            'port' => '3306',
            'database' => 'd0407c9a',
            'username' => 'd0407c9a',
            'password' => 'ZGZ2dhKeeZ2heNVP5jCG',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'dep.de' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd042e65d',
            'username' => 'd042e65d',
            'password' => 'DuFqJQCzvhdNtALB6JRu',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'chest.de' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd043807f',
            'username' => 'd043807f',
            'password' => 'HgEe4xwfAW7oyhTNM5Wk',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.lv' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd041d2f2',
            'username' => 'd041d2f2',
            'password' => '37DW9AZXQnKh2WrbWcWt',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.nl' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd041a43a',
            'username' => 'd041a43a',
            'password' => 'pfizvFFvJsD8n2akbtjv',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.it' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd041c6f1',
            'username' => 'd041c6f1',
            'password' => 'MHNASFmEoTsm5KNnsw3q',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.li' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd041d2c2',
            'username' => 'd041d2c2',
            'password' => 'YpLNGGAhTzE3H6YZhB8h',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'xl.es' => [
            'driver' => 'mysql',
            'host' => 'w01f7ee0.kasserver.com',
            'port' => '3306',
            'database' => 'd041c713',
            'username' => 'd041c713',
            'password' => '9w7X7eCqNSx8xB2i8qQF',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DB_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8'),
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8'),
            'prefix' => '',
            'prefix_indexes' => true,
        ],
    ],

    'migrations' => [
        'table' => 'migrations',
        'update_date_on_publish' => true,
    ],

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_') . '_database_'),
            'persistent' => env('REDIS_PERSISTENT', false),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],

];
